version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nextjs-app
permissions:
  - object: /var/www/nextjs-app
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu
